
library(shiny)
library(shinyjs)
library(shinydashboard)
library(shinycssloaders)
library(shinythemes)
library(htmlwidgets)
library(dplyr)
library(readxl)
library(DT)
library(igraph)
library(ggplot2)
library(networkD3)
library(reshape2)
library(plotly)
library(geneHapR)
library(grid)
library(reshape2)
library(GenomicRanges)
library(IRanges)
library(RColorBrewer)
library(CMplot)
library(bigmemory)
library(rMVP)
library(jpeg)
library(png)
library(magick)
library(pdftools)
library(ggPlantmap)
library(patchwork)
Sys.setlocale(category = "LC_ALL", locale = "en_US.UTF-8")





shinyApp(source("./ui/ui.R"),source("./server/server.R")$value)
